// AUTO-GENERATED — do not edit directly.
// Source: src/theme/tokens.json  |  Generator: scripts/generate-tokens.mjs
// Run `npm run generate-tokens` to update.

import { css } from 'react-strict-dom';
import { tokens } from '../tokens.css';

export const darkThemeStyle = css.createTheme(tokens, {
    colorBackground: '#080A05',
    colorSurfacePrimary: '#15180E',
    colorSurfaceSecondary: '#FDCA40',
    colorPrimary: '#B0D944',
    colorSecondary: '#8AE081',
    colorAccentHover: '#BAE061',
    colorAccentActive: '#98C328',
    colorSurfaceHover: '#212814',
    colorSurfaceElevatedOnInteraction: '#2C3618',
    colorSurfaceDisabled: '#212814',
    colorSurfaceDestructiveElevated: '#D13B3D',
    colorSurfaceDestructive: '#421010',
    colorTextPrimary: '#FFFFFF',
    colorOnPrimary: '#08090C',
    colorTextSecondary: '#BDC3AC',
    colorTextDisabled: '#435123',
    colorBorderPrimary: '#212814',
    colorBorderSecondary: '#2C3618',
    colorSurfaceError: '#D1383D',
    colorSurfaceWarning: '#D7D245',
    colorFocusRing: '#B0D944',
    backgroundSnackbar: '#FFFFFF',
    spacing4: '4px',
    spacing6: '6px',
    spacing8: '8px',
    spacing12: '12px',
    spacing16: '16px',
    spacing20: '20px',
    spacing24: '24px',
    spacing32: '32px',
    spacing40: '40px',
    radius8: '8px',
    radius16: '16px',
    radius20: '20px',
    radius26: '26px',
    fontPrimary: 'Inter',
    fontDisplay: 'Humble Nostalgia',
    fontSize12: '12px',
    fontSize14: '14px',
    fontSize16: '16px',
    fontSize24: '24px',
    fontSize28: '28px',
    weightRegular: '400',
    weightMedium: '500',
});
