// AUTO-GENERATED — do not edit directly.
// Source: src/theme/tokens.json  |  Generator: scripts/generate-tokens.mjs
// Run `npm run generate-tokens` to update.

import { css } from 'react-strict-dom';
import { tokens } from '../tokens.css';

export const lightThemeStyle = css.createTheme(tokens, {
    colorBackground: '',
    colorSurfacePrimary: '',
    colorSurfaceSearchField: '',
    colorSurfaceSecondary: '',
    colorPrimary: '',
    colorSecondary: '',
    colorAccentHover: '',
    colorAccentActive: '',
    colorSurfaceHover: '',
    colorSurfaceElevatedOnInteraction: '',
    colorSurfaceDisabled: '',
    colorSurfaceDestructiveElevated: '',
    colorSurfaceDestructive: '',
    colorTextPrimary: '',
    colorOnPrimary: '',
    colorTextSearchField: '',
    colorTextSecondary: '',
    colorTextDisabled: '',
    colorTextDestructive: '',
    colorBorderPrimary: '',
    colorBorderSearchField: '',
    colorBorderSecondary: '',
    colorBorderTertiary: '',
    colorSurfaceError: '',
    colorSurfaceWarning: '',
    colorFocusRing: '',
    colorTextTertiary: '',
    colorLinkText: '',
    backgroundSnackbar: '',
    spacing2: '2px',
    spacing4: '4px',
    spacing6: '6px',
    spacing8: '8px',
    spacing10: '10px',
    spacing12: '12px',
    spacing16: '16px',
    spacing20: '20px',
    spacing24: '24px',
    spacing32: '32px',
    spacing40: '40px',
    spacing48: '48px',
    spacing60: '60px',
    radius6: '6px',
    radius8: '8px',
    radius16: '16px',
    radius20: '20px',
    radius26: '26px',
    shadowMenu: '0 185px 52px 0 rgba(8,10,5,0.01), 0 118px 47px 0 rgba(8,10,5,0.06), 0 67px 40px 0 rgba(8,10,5,0.20), 0 30px 30px 0 rgba(8,10,5,0.34), 0 7px 16px 0 rgba(8,10,5,0.39)',
    fontPrimary: 'Inter',
    fontDisplay: 'Humble Nostalgia',
    fontSize12: '12px',
    fontSize14: '14px',
    fontSize16: '16px',
    fontSize24: '24px',
    fontSize28: '28px',
    weightRegular: '400',
    weightMedium: '500',
});
