import { css } from 'react-strict-dom';
import { tokens } from '../../theme/tokens.css';

const backdropFadeIn = css.keyframes({
    '0%': { opacity: 0 },
    '100%': { opacity: 1 },
});

const dialogEnter = css.keyframes({
    '0%': {
        opacity: 0,
        transform: 'translateY(8px) scale(0.98)',
    },
    '100%': {
        opacity: 1,
        transform: 'translateY(0) scale(1)',
    },
});

export const styles = css.create({
    modalLayer: {
        position: 'fixed',
        inset: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        paddingInline: tokens.spacing48,
        paddingBlock: tokens.spacing40,
        boxSizing: 'border-box',
        zIndex: 999,
    },
    backdrop: {
        position: 'absolute',
        inset: 0,
        backgroundColor: 'rgba(8, 10, 5, 0.72)',
        animationName: backdropFadeIn,
        animationDuration: '180ms',
        animationTimingFunction: 'ease-out',
        animationFillMode: 'both',
    },
    dialogPositioner: {
        position: 'relative',
        zIndex: 1,
        width: '100%',
        maxWidth: 520,
        maxHeight: '100%',
        display: 'flex',
        justifyContent: 'center',
        animationName: dialogEnter,
        animationDuration: '180ms',
        animationTimingFunction: 'ease-out',
        animationFillMode: 'both',
    },
    root: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        alignItems: 'flex-start',
        boxSizing: 'border-box',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: tokens.colorBorderPrimary,
        borderRadius: tokens.radius8,
        backgroundColor: tokens.colorSurfacePrimary,
        overflow: 'hidden',
        maxHeight: '100%',
    },
    header: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        boxSizing: 'border-box',
        gap: tokens.spacing12,
        paddingBlock: tokens.spacing12,
        paddingInline: tokens.spacing16,
    },
    title: {
        display: 'flex',
        color: tokens.colorTextPrimary,
        fontFamily: tokens.fontPrimary,
        fontSize: tokens.fontSize14,
        fontWeight: tokens.weightMedium,
        lineHeight: 'normal',
        minWidth: 0,
        flex: 1,
    },
    closeButton: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: tokens.spacing24,
        height: tokens.spacing24,
        borderWidth: 0,
        backgroundColor: 'transparent',
        color: tokens.colorTextPrimary,
        cursor: 'pointer',
        padding: 0,
        borderRadius: tokens.radius8,
        flexShrink: 0,
        ':hover': {
            backgroundColor: tokens.colorSurfaceHover,
        },
        ':active': {
            backgroundColor: tokens.colorSurfaceElevatedOnInteraction,
        },
        ':focus-visible': {
            outlineWidth: 2,
            outlineStyle: 'solid',
            outlineColor: tokens.colorFocusRing,
            outlineOffset: 2,
        },
    },
    closeIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        lineHeight: 0,
    },
    body: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        boxSizing: 'border-box',
        padding: tokens.spacing16,
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: tokens.colorBorderPrimary,
        color: tokens.colorTextPrimary,
        fontFamily: tokens.fontPrimary,
        fontSize: tokens.fontSize14,
        fontWeight: tokens.weightRegular,
        lineHeight: 'normal',
        overflowY: 'auto',
        overscrollBehavior: 'contain',
        flex: 1,
    },
    footer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        width: '100%',
        boxSizing: 'border-box',
        gap: tokens.spacing8,
        paddingBlock: tokens.spacing12,
        paddingInline: tokens.spacing16,
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: tokens.colorBorderPrimary,
    },
});
